#!/bin/sh

DIR=$HOME/.local/share/OGAT

test -d "$DIR" || mkdir -p "$DIR"
test -f "$DIR/OGAT" || cp /usr/lib/ofguardsandthieves/ofguardsandthieves "$DIR/OGAT"
test -d "$DIR/OGAT_Data" || cp -r /usr/lib/ofguardsandthieves/ofguardsandthieves_Data "$DIR/OGAT_Data"
test -x "$DIR/OGAT" || chmod a+x "$DIR/OGAT"

"$DIR/OGAT"

